### ISSUE TITLE
Откуда взять ID региона?

### ISSUE THREAD

**Issue by Ahaenor** [nextgis/reformagkh#10]
Добрый день.

Изучаем ваш граббер. Проблема в том, что, согласно ману, ID региона - число.
Но на https://www.reformagkh.ru/ мы не видим числового ID (ближайшее, что нашли, это guid - длинная строка).

Где можно увидеть ID региона/города/и т.д.?
Спасибо заранее.

**Comment by simgislab** [comment]
Идентификатор можно взять или в atd.csv или непосредственно из ссылки (tid) вида https://www.reformagkh.ru/myhouse?tid=2208192

обновил readme
