### ISSUE TITLE
No data at all

### ISSUE THREAD

**Issue by obtim** [nextgis/reformagkh#13]
Win 7 x64 SP1 Rus+all updates
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
No antivirus software
1. Tor Browser 6.0.6 - running
2. Try python c:\123\get_reformagkh_data-v3.py 2280999 c:\123\housedata.csv -of html
3. Got only housedata.csv with header LAT,LON,HOUSE_ID,ADDRESS,YEAR,LASTUPDATE,SERVICEDATE_START,SERIE,HOUSE_TYPE,CAPFOND,MGMT_COMPANY,MGMT_COMPANY_LINK,AVAR,LEVELS_MAX,LEVELS_MIN,DOORS,ROOM_COUNT,ROOM_COUNT_LIVE,ROOM_COUNT_NONLIVE,AREA,AREA_LIVE,AREA_NONLIVE,AREA_GEN,AREA_LAND,AREA_PARK,CADNO,ENERGY_CLASS,BLAG_PLAYGROUND,BLAG_SPORT,BLAG_OTHER,OTHER
in c:\123\
No data at all

**Comment by brusnika** [comment]
line 72 . In the def get_content a value "res" can't decide from request. After request to 'link', res='', and displayed the exception ('Session time out').

**Comment by simgislab** [comment]
@obtim checked your case, all works fine, try updating and running again
@brusnika v2 is not supported anymore, can't comment on TOR problems you seems to be having

reopen if necessary with more info
